name: Jeff's Test Site
title: Jeff's Test Site
description: Web Developer from Somewhere
theme: jekyll-theme-minimal
branch: gh-pages

docs_list_title: TEST NAV
docs:

- title: Home
  url: /

- title: Test
  url: /test

- title: Plain
  url: index2.html

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  css_class: 'highlight'