name: Jeff's Test Site
title: Jeff's Test Site
description: Web Developer from Somewhere
theme: jekyll-theme-minimal
branch: gh-pages

relative_links:
  enabled:     true
  collections: false

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  css_class: 'highlight'